apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: go.where.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-world-service
          servicePort: 80
